# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Clean
version:      2.00_5
version_from: Clean.pm
installdirs:  site
requires:
    HTML::Clean:                   0.8
    mod_perl:                      1.9909

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
